#!/usr/bin/env python3
"""Export word list for GAS batch GA warmup (BatchWords.gs + batch_words.csv)."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WORDLIST = ROOT / "data" / "wordlist_with_neighbors_slim.json"
OUT_GS = ROOT / "gas" / "BatchWords.gs"
OUT_CSV = ROOT / "gas" / "batch_words.csv"


def main():
    with WORDLIST.open(encoding="utf-8") as f:
        words = [row["w"] for row in json.load(f)]

    OUT_CSV.write_text("word\n" + "\n".join(words) + "\n", encoding="utf-8")

    lines = [
        "/**",
        " * AUTO-GENERATED by scripts/export_batch_words.py — do not edit.",
        f" * {len(words)} words from wordlist_with_neighbors_slim.json",
        " */",
        "var BATCH_WORD_LIST = [",
    ]
    for w in words:
        lines.append(f"  {json.dumps(w)},")
    lines.append("];")
    lines.append("")
    OUT_GS.write_text("\n".join(lines), encoding="utf-8")

    print(f"Wrote {len(words)} words -> {OUT_GS.name}, {OUT_CSV.name}")


if __name__ == "__main__":
    main()
